[package]
name = "katars"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.49", features = ["full"] }
quote = "1.0"
jni = "0.21.1"
proc-macro2 = "1.0.78"
serde_json = "1.0.113"
serde = { version = "1.0.196", features = ["derive"] }
